/* tslint:disable */
/* eslint-disable */
/**
 * Kupsilla Data Platform dictionary engine as a service
 * Swagger for \'Kupsilla Data Platform dictionary engine as a service\'
 *
 * The version of the OpenAPI document: 0.1.0-df9ccc8-df9ccc8-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * An object representing a translated text content
 * @export
 * @interface TranslatedTextContentDTO
 */
export interface TranslatedTextContentDTO {
    /**
     * ISO 639 standard language code in lowercase
     * @type {string}
     * @memberof TranslatedTextContentDTO
     */
    language_code: string;
    /**
     * Translated text in the language corresponding to the language code
     * @type {string}
     * @memberof TranslatedTextContentDTO
     */
    text: string;
}
